server:
  port: ${PORT:${SERVER_PORT:8080}}  # Railway uses PORT, fallback to SERVER_PORT
  servlet:
    context-path: /api

spring:
  application:
    name: portfolio-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: true

# EXPLICIT Management Configuration for Production
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
  server:
    port: ${PORT:${SERVER_PORT:8080}}  # Same port as main app

# Logging
logging:
  level:
    com.portfolio: INFO
    org.springframework.security: WARN
    org.springframework.boot.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# CORS
cors:
  origins: ${CORS_ORIGINS:https://portfolio.debojit.dev}
