server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: portfolio-backend

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:portfolio_user}
    password: ${DB_PASSWORD:portfolio_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: false

  sql:
    init:
      mode: always
      continue-on-error: false

  # Virtual Threads (Java 21 Feature)
  threads:
    virtual:
      enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173,https://*.vercel.app,https://*.netlify.app}

# Portfolio Configuration
portfolio:
  version: 1.0.0
  author: Debojit Chakraborty
  enable-sample-data: true
  support-email: devchakraborty9914@gmail.com

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000  # 24 hours

# Logging Configuration
logging:
  level:
    com.portfolio: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_LOG_LEVEL:TRACE}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/portfolio-backend.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    docExpansion: none
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  pathsToMatch: /portfolio/**, /auth/**

# API Documentation
api:
  title: Portfolio Backend API
  description: Backend API for portfolio management system
  version: 1.0.0
  author: Debojit Chakraborty

